export const products = [
  {
    id: 1,
    title: "RTX 5090 Gaming PC",
    category: "Gaming PC",
    price: "$4,999",
    image: "/images/hero-pc.jpg",
    cpu: "Intel Core i9-14900K",
    gpu: "RTX 5090",
    ram: "64GB DDR5",
    storage: "2TB NVMe SSD",
  },
  {
    id: 2,
    title: "RTX 5080 Creator PC",
    category: "Creator PC",
    price: "$3,799",
    image: "/images/hero-pc.jpg",
    cpu: "Intel Core i9-14900K",
    gpu: "RTX 5090",
    ram: "64GB DDR5",
    storage: "2TB NVMe SSD",
  },
  {
    id: 3,
    title: "RTX 5070 Budget Beast",
    category: "Gaming PC",
    price: "$2,299",
    image: "/images/hero-pc.jpg",
    cpu: "Intel Core i9-14900K",
    gpu: "RTX 5090",
    ram: "64GB DDR5",
    storage: "2TB NVMe SSD",
  },
  {
    id: 4,
    title: "Intel i9 Ultimate Build",
    category: "Workstation",
    price: "$5,299",
    image: "/images/hero-pc.jpg",
    cpu: "Intel Core i9-14900K",
    gpu: "RTX 5090",
    ram: "64GB DDR5",
    storage: "2TB NVMe SSD",
  },

  {
    id: 5,
    title: "AMD Ryzen 9 Monster",
    category: "Gaming PC",
    price: "30,500,000",
    image: "/images/hero-pc.jpg",
    cpu: "Intel Core i9-14900K",
    gpu: "RTX 5090",
    ram: "64GB DDR5",
    storage: "2TB NVMe SSD",
  },
  {
    id: 6,
    title: "Streaming Pro Setup",
    category: "Streaming",
    price: "$2,999",
    image: "/images/hero-pc.jpg",
    cpu: "Intel Core i9-14900K",
    gpu: "RTX 5090",
    ram: "64GB DDR5",
    storage: "2TB NVMe SSD",
  },
];